#pragma once

////
//
//      STM32U5 peripherals
//
///

#include "adc.h"
#include "adf.h"
#include "aes.h"
#include "comp.h"
#include "cordic.h"
#include "crc.h"
#include "crs.h"
#include "dac.h"
#include "dbgmcu.h"
#include "dcache.h"
#include "dcmi.h"
#include "dlyb.h"
#include "dma2d.h"
#include "exti.h"
#include "fdcan.h"
#include "flash.h"
#include "fmac.h"
#include "fmc.h"
#include "gpdma.h"
#include "gpio.h"
#include "gtzc.h"
#include "hash.h"
#include "i2c.h"
#include "icache.h"
#include "iwdg.h"
#include "lpdma.h"
#include "lpgpio.h"
#include "lptim.h"
#include "lpuart.h"
#include "mdf.h"
#include "octospi.h"
#include "opamp.h"
#include "otfdec.h"
#include "otg_fs.h"
#include "pka.h"
#include "pssi.h"
#include "pwr.h"
#include "ramcfg.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "saes.h"
#include "sai.h"
#include "sdmmc.h"
#include "spi.h"
#include "syscfg.h"
#include "tamp.h"
#include "tim.h"
#include "tsc.h"
#include "ucpd.h"
#include "usart.h"
#include "vref.h"
#include "wwdg.h"

