#pragma once

////
//
//      STM32F4 peripherals
//
////

#include "adc.h"
#include "aes.h"
#include "can.h"
#include "crc.h"
#include "cryp.h"
#include "dac.h"
#include "dbg.h"
#include "dcmi.h"
#include "dfsdm.h"
#include "dma.h"
#include "dma2d.h"
#include "dsihost.h"
#include "exti.h"
#include "ethernet.h"
#include "flash.h"
#include "fpu.h"
#include "fsmc.h"
#include "gpio.h"
#include "hash.h"
#include "hdmi_cec.h"
#include "i2c.h"
#include "iwdg.h"
#include "lptim.h"
#include "ltdc.h"
#include "mpu.h"
#include "nvic.h"
#include "pwr.h"
#include "quadspi.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "sai1.h"
#include "scb.h"
#include "sdio.h"
#include "spdif_rx.h"
#include "spi.h"
#include "stk.h"
#include "syscfg.h"
#include "tim.h"
#include "usart.h"
#include "usb_otg_fs.h"
#include "usb_otg_hs.h"
#include "wwdg.h"

