#pragma once

////
//
//      STM32L5 peripherals
//
////

#include "adc.h"
#include "aes.h"
#include "comp.h"
#include "crc.h"
#include "crs.h"
#include "dac.h"
#include "dbgmcu.h"
#include "dcb.h"
#include "dfsdm.h"
#include "dma.h"
#include "dmamux.h"
#include "exti.h"
#include "fdcan.h"
#include "fmc.h"
#include "flash.h"
#include "gpio.h"
#include "gtzc.h"
#include "i2c.h"
#include "icache.h"
#include "iwdg.h"
#include "lptim.h"
#include "nvic.h"
#include "opamp.h"
#include "otfdec.h"
#include "octospi.h"
#include "pka.h"
#include "pwr.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "sdmmc.h"
#include "sec_gtzc.h"
#include "spi.h"
#include "syscfg.h"
#include "tamp.h"
#include "tim.h"
#include "tsc.h"
#include "ucpd.h"
#include "usart.h"
#include "usb.h"
#include "vref.h"
#include "wwdg.h"

