#pragma once

////
//
//      STM32H7 peripherals
//
///

#include "ac.h"
#include "adc.h"
#include "art.h"
#include "axi.h"
#include "bdma.h"
#include "cec.h"
#include "comp1.h"
#include "crc.h"
#include "crs.h"
#include "cryp.h"
#include "dac.h"
#include "dbgmcu.h"
#include "dcmi.h"
#include "dfsdm.h"
#include "dlyb.h"
#include "dma.h"
#include "dma2d.h"
#include "dmamux.h"
#include "dsihost.h"
#include "ethernet.h"
#include "exti.h"
#include "fdcan.h"
#include "flash.h"
#include "fmc.h"
#include "fpu.h"
#include "gpio.h"
#include "hash.h"
#include "hrtim.h"
#include "hsem.h"
#include "i2c.h"
#include "iwdg.h"
#include "jpeg.h"
#include "lptim.h"
#include "lpuart.h"
#include "ltdc.h"
#include "mdios.h"
#include "mdma.h"
#include "mpu.h"
#include "nvic.h"
#include "octospi.h"
#include "octospii_o_manager.h"
#include "opamp.h"
#include "otfdec.h"
#include "pf.h"
#include "pwr.h"
#include "quadspi.h"
#include "ramecc.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "scb.h"
#include "sdmmc.h"
#include "spdifrx.h"
#include "spi.h"
#include "stk.h"
#include "swpmi.h"
#include "syscfg.h"
#include "tim.h"
#include "tims.h"
#include "usart.h"
#include "usb_otg_hs.h"
#include "vrefbuf.h"
#include "wwdg.h"

