#pragma once

////
//
//      STM32G4 peripherals
//
///

#include "adc.h"
#include "aes.h"
#include "comp.h"
#include "cordic.h"
#include "crc.h"
#include "crs.h"
#include "dac.h"
#include "dbgmcu.h"
#include "dma.h"
#include "dmamux.h"
#include "exti.h"
#include "fdcan.h"
#include "flash.h"
#include "fmac.h"
#include "fmc.h"
#include "fpu.h"
#include "gpio.h"
#include "hrtim.h"
#include "i2c.h"
#include "iwdg.h"
#include "lptim.h"
#include "lpuart.h"
#include "mpu.h"
#include "nvic.h"
#include "opamp.h"
#include "pwr.h"
#include "quadspi.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "scb.h"
#include "spi.h"
#include "stk.h"
#include "syscfg.h"
#include "tamp.h"
#include "tim.h"
#include "uart.h"
#include "ucpd.h"
#include "usart.h"
#include "usb.h"
#include "vrefbuf.h"
#include "wwdg.h"

