#pragma once

////
//
//      STM32L4 peripherals
//
///

#include "adc.h"
#include "aes.h"
#include "can.h"
#include "comp.h"
#include "crc.h"
#include "crs.h"
#include "dac.h"
#include "dbgmcu.h"
#include "dcmi.h"
#include "dfsdm.h"
#include "dma.h"
#include "dma2d.h"
#include "exti.h"
#include "firewall.h"
#include "flash.h"
#include "fmc.h"
#include "fpu.h"
#include "gpio.h"
#include "hash.h"
#include "i2c.h"
#include "iwdg.h"
#include "lcd.h"
#include "lptim.h"
#include "lpuart.h"
#include "mpu.h"
#include "nvic.h"
#include "opamp.h"
#include "pwr.h"
#include "quadspi.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "scb.h"
#include "sdio.h"
#include "spi.h"
#include "stk.h"
#include "swpmi.h"
#include "syscfg.h"
#include "tim.h"
#include "tsc.h"
#include "usart.h"
#include "usb.h"
#include "usb_otg_fs.h"
#include "vref.h"
#include "wwdg.h"

