#pragma once

////
//
//      STM32F7 peripherals
//
///

#include "ac.h"
#include "adc.h"
#include "aes.h"
#include "can.h"
#include "cec.h"
#include "crc.h"
#include "cryp.h"
#include "dac.h"
#include "dbg.h"
#include "dbgmcu.h"
#include "dcmi.h"
#include "dfsdm.h"
#include "dma.h"
#include "dma2d.h"
#include "dsi.h"
#include "ethernet.h"
#include "exti.h"
#include "flash.h"
#include "fmc.h"
#include "fpu.h"
#include "gpio.h"
#include "hash.h"
#include "i2c.h"
#include "iwdg.h"
#include "jpeg.h"
#include "lptim.h"
#include "ltdc.h"
#include "mdios.h"
#include "mpu.h"
#include "nvic.h"
#include "pf.h"
#include "pwr.h"
#include "quadspi.h"
#include "rcc.h"
#include "rng.h"
#include "rtc.h"
#include "sai.h"
#include "scb.h"
#include "sdmmc.h"
#include "spdif_rx.h"
#include "spi.h"
#include "stk.h"
#include "syscfg.h"
#include "tim.h"
#include "usart.h"
#include "usbphyc.h"
#include "usb_otg_fs.h"
#include "usb_otg_hs.h"
#include "wwdg.h"

