_build/corona/peripheral.cpp.o: ../../../..\corona\src\peripheral.cpp \
 ../../../..\corona\include/corona.h \
 ../../../..\corona\include/register.h \
 ../../../..\corona\include/stm32/stm32.h \
 ../../../..\corona\include\stm32\STM32G0/device/mcu.h \
 ../../../..\corona\include\stm32\STM32G0/device/peripheral.h \
 ../../../..\corona\include\stm32\STM32G0/device/interrupt.h \
 ../../../..\corona\include\stm32\STM32G0/device/all.h \
 ../../../..\corona\include\stm32\STM32G0/device/adc.h \
 ../../../..\corona\include\stm32\STM32G0/device/aes.h \
 ../../../..\corona\include\stm32\STM32G0/device/cec.h \
 ../../../..\corona\include\stm32\STM32G0/device/comp1.h \
 ../../../..\corona\include\stm32\STM32G0/device/crc.h \
 ../../../..\corona\include\stm32\STM32G0/device/dac.h \
 ../../../..\corona\include\stm32\STM32G0/device/dbg.h \
 ../../../..\corona\include\stm32\STM32G0/device/dma.h \
 ../../../..\corona\include\stm32\STM32G0/device/dmamux.h \
 ../../../..\corona\include\stm32\STM32G0/device/exti.h \
 ../../../..\corona\include\stm32\STM32G0/device/fpu.h \
 ../../../..\corona\include\stm32\STM32G0/device/flash.h \
 ../../../..\corona\include\stm32\STM32G0/device/gpio.h \
 ../../../..\corona\include\stm32\STM32G0/device/i2c.h \
 ../../../..\corona\include\stm32\STM32G0/device/iwdg.h \
 ../../../..\corona\include\stm32\STM32G0/device/lptim.h \
 ../../../..\corona\include\stm32\STM32G0/device/mpu.h \
 ../../../..\corona\include\stm32\STM32G0/device/nvic.h \
 ../../../..\corona\include\stm32\STM32G0/device/pwr.h \
 ../../../..\corona\include\stm32\STM32G0/device/rcc.h \
 ../../../..\corona\include\stm32\STM32G0/device/rng.h \
 ../../../..\corona\include\stm32\STM32G0/device/rtc.h \
 ../../../..\corona\include\stm32\STM32G0/device/scb.h \
 ../../../..\corona\include\stm32\STM32G0/device/spi.h \
 ../../../..\corona\include\stm32\STM32G0/device/stk.h \
 ../../../..\corona\include\stm32\STM32G0/device/syscfg.h \
 ../../../..\corona\include\stm32\STM32G0/device/tamp.h \
 ../../../..\corona\include\stm32\STM32G0/device/tim.h \
 ../../../..\corona\include\stm32\STM32G0/device/ucpd.h \
 ../../../..\corona\include\stm32\STM32G0/device/usart.h \
 ../../../..\corona\include\stm32\STM32G0/device/vrefbuf.h \
 ../../../..\corona\include\stm32\STM32G0/device/wwdg.h \
 ../../../..\corona\include\stm32\STM32G0/device/peripheral.cpp
